`timescale 1ns / 1ps

module counter_top(
    input clk,
    input i_inc,
    input i_reset,
    output [3:0] an,
    output dp,
    output [6:0] seg
);


logic locked;

// Clock module generated by Clocking Wizard
/*
logic clk_50;
clk_wiz_50(.clk_in1(clk),
            .reset(1'b0),
            .locked(locked),
            .clk_out_50(clk_50));
*/

/*
logic clk_35;
clk_wiz_35(.clk_in1(clk),
            .reset(1'b0),
            .locked(locked),
            .clk_out_35(clk_35));
*/

logic clk_gen;

clk_wiz_gen(.clk_in1(clk),
            .reset(1'b0),
            .locked(locked),
            .clk_out(clk_gen));        

reg [0:31] out;
counter counter_instance(.clk(clk_gen),
    .i__inc(i_inc),
    .i__reset(i_reset),
    .o__count__next(out));

display u (                    
    .in_count(out),
    .clk(clk_gen),
    .clr(i_reset),
    .a_to_g(seg),
    .an(an),
    .dp(dp)
);

endmodule